name: SinceEnchantments
version: '${version}'
main: net.danh.sinceenchantments.SinceEnchantments
api-version: '1.21'
load: POSTWORLD
folia-supported: true
authors: [ VoChiDanh ]
website: https://gitlab.com/sincerpg/SinceEnchantments/-/wikis/home
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    MythicLib:
      load: BEFORE
      required: false
    MMOCore:
      load: BEFORE
      required: false
    AdvancedEnchantments:
      load: BEFORE
      required: false
    CrazyEnchantments:
      load: BEFORE
      required: false
    ExcellentEnchants:
      load: BEFORE
      required: false
    EnchantsSquared:
      load: BEFORE
      required: false
